version: '3.4'

services:
  catalogDb:
    container_name: catalogdatabase
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
  basketDb:
    container_name: basketdatabase
    restart: always
    ports:
      - "6379:6379"
  discountDb:
    container_name: discountdatabase
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
  orderDb:
    container_name: orderdatabase
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - "./data-mssql:/var/opt/mssql/data"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin12345
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Catalog.API.pfx
      - "ConnectionStrings:MongoDatabaseSettings:mongoConnection=mongodb://catalogdatabase:27017"
    depends_on:
      - catalogdatabase
    ports:
      - "8081:80"
      - "8000:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Basket.API.pfx
      - "CacheSettings:ConnectionString=basketdatabase:6379"
      - "GrpcSettings:DiscountUrl=https://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdatabase
    ports:
      - "8082:80"
      - "8001:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Discount.API.pfx
      - "DatabaseSettings:ConnectionString= Server=discountdatabase;Port=5432;Database=DiscoundDb;User Id=admin;Password=admin12345"
    depends_on:
      - discountdatabase
    ports:
      - "8083:80"
      - "8002:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Grpc.pfx
      - "DatabaseSettings:ConnectionString=Server=discountdatabase;Port=5432;Database=DiscoundDb;User Id=admin;Password=admin12345"
    depends_on:
      - discountdatabase
    ports:
      - "8084:80"
      - "8003:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/orderAPI.pfx
      - "ConnectionStrings:OrderingConnectionString=Server=orderdatabase;Database=OrderDb;User Id=sa;Password=yourStrong(!)Password"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - orderdatabase
    ports:
      - "8085:80"
      - "8004:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
